# -*- coding: utf-8 -*-
"""Копия блокнота "Operations.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1itgOGZHGft4PSk4YqlHulLXtECFA17Jg
"""

# строковые переменные

my_str = "Привет"
print(type(my_str))
print(id(my_str))
print(my_str)

my_str = "Пока"
print(type(my_str))
print(id(my_str))
print(my_str)

# булевы значения
x = True
y = False

print(x and y)
print(x or y)
print(not x)

# целочисленные переменные
a = 10
b = 3

print(a + b)  # Сложение: 13
print(a - b)  # Вычитание: 7
print(a * b)  # Умножение: 30
print(a / b)  # Деление: 3.3333...
print(a // b) # Целочисленное деление: 3
print(a % b)  # Остаток от деления: 1
print(a ** b) # Возведение в степень: 1000

# числа с плавающей точкой
num_int = 10
num_float = float(num_int)
print(num_float)  # Вывод: 10.0

num_str = "3.14"
num_float_from_str = float(num_str)
print(num_float_from_str)  # Вывод: 3.14
print(type(num_float_from_str))

# массивоподобные структуры

# списки
My_list = [1,2,3,4,10]
print(My_list)
print(type(My_list))
My_list[0]="Один"
print(My_list)
My_list.append(10.25)
print(My_list)

# кортежи
my_tuple = (1, 2, 3, "четыре", 5.0)
print(my_tuple)

# словари
my_dict = {"age": 54, "name": "alex", "number":5}
print(my_dict)

# множества
my_set = {1, 2, 3, 4, 5}
another_set = set([1, 2, 2, 3])
print(another_set)

# операции

a = 100
b = 500

# сложение
print(a + b)







# вычитание
print(a - b)


# умножение
print(a * b)


# деление
print(a / b)
print(a // b)

# остаток от деления
print(a % b)

# возведение в степень
print(a ** b)

# форматирование строк

# format
name = "Alice"
age = 30

formatted_string = "Имя: {}, Возраст: {}".format(name, age)
print(formatted_string)
formatted_string = "Возраст: {1}, Имя: {0}".format(name, age)
print(formatted_string)
formatted_string = "Имя: {name}, Возраст: {age}".format(name=name, age=age)
print(formatted_string)

# f-строки
formatted_string = f"Имя: {name}, Возраст: {age}"
print(formatted_string)

a = 5
b = 10
formatted_string = f"Сумма: {a + b}"
print(formatted_string)